setup git deploy & ci for hexo
idjs/idjs.github.io pull request #3
Opened 2016-12-07 06:14 UTC by anggiaj

![screen shot 2016-12-07 at 1 10 03 pm](https://cloud.githubusercontent.com/assets/367079/20956831/f76aa944-bc7e-11e6-9b31-858cb0614fc1.png)

Harus setup circleci-nya

2016-12-07 06:24 UTC, tianp requested changes

2016-12-07 06:24 UTC, tianp commented on circle.yml
> +    version: v6.1.0
tolong pakai LTS yang latest ya: v6.9.2

2016-12-07 06:24 UTC, tianp commented on package.json
>    "version": "0.0.0",
mulai start version dari 0.1.0

2016-12-07 07:53 UTC, raitucarp submitted a review, later dismissed

2016-12-07 10:24 UTC, tianp approved these changes

2016-12-07 10:24 UTC, tianp commented
mantap! 🎉

2016-12-07 12:04 UTC, merged

2016-12-07 14:00 UTC, anggiaj commented
@tianp @raitucarp @oknoorap yg punya `admin` privilege tolong di setup CircleCI-nya ya, thanks

2016-12-08 04:36 UTC, tianp commented
@anggiaj saya sudah setup CircleCI sebelumnya, ada masalah di integrasinya kah?